package todo;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import gc.WeakReference;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

import salsa.resources.SystemService;

import salsa.resources.ActorService;

// End SALSA compiler generated import delcarations.

import java.time.Duration;
import java.time.Instant;
import java.util.Date;
import java.sql.Timestamp;
import java.util.*;

public class CausalAdvancedTodo extends UniversalActor  {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getTheater().getLocation() + System.getProperty("identifier"));
		}
		RunTime.receivedMessage();
		CausalAdvancedTodo instance = (CausalAdvancedTodo)new CausalAdvancedTodo(uan, ual,null).construct();
		gc.WeakReference instanceRef=new gc.WeakReference(uan,ual);
		{
			Object[] _arguments = { args };

			//preAct() for local actor creation
			//act() for remote actor creation
			if (ual != null && !ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {instance.send( new Message(instanceRef, instanceRef, "act", _arguments, false) );}
			else {instance.send( new Message(instanceRef, instanceRef, "preAct", _arguments, false) );}
		}
		RunTime.finishedProcessingMessage();
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new CausalAdvancedTodo(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return CausalAdvancedTodo.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new CausalAdvancedTodo(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return CausalAdvancedTodo.getReferenceByLocation(new UAL(ual)); }
	public CausalAdvancedTodo(boolean o, UAN __uan)	{ super(false,__uan); }
	public CausalAdvancedTodo(boolean o, UAL __ual)	{ super(false,__ual); }
	public CausalAdvancedTodo(UAN __uan,UniversalActor.State sourceActor)	{ this(__uan, null, sourceActor); }
	public CausalAdvancedTodo(UAL __ual,UniversalActor.State sourceActor)	{ this(null, __ual, sourceActor); }
	public CausalAdvancedTodo(UniversalActor.State sourceActor)		{ this(null, null, sourceActor);  }
	public CausalAdvancedTodo()		{  }
	public CausalAdvancedTodo(UAN __uan, UAL __ual, Object obj) {
		//decide the type of sourceActor
		//if obj is null, the actor must be the startup actor.
		//if obj is an actorReference, this actor is created by a remote actor

		if (obj instanceof UniversalActor.State || obj==null) {
			  UniversalActor.State sourceActor;
			  if (obj!=null) { sourceActor=(UniversalActor.State) obj;}
			  else {sourceActor=null;}

			  //remote creation message sent to a remote system service.
			  if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {
			    WeakReference sourceRef;
			    if (sourceActor!=null && sourceActor.getUAL() != null) {sourceRef = new WeakReference(sourceActor.getUAN(),sourceActor.getUAL());}
			    else {sourceRef = null;}
			    if (sourceActor != null) {
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual!=null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());
			      activateGC();
			    }
			    createRemotely(__uan, __ual, "todo.CausalAdvancedTodo", sourceRef);
			  }

			  // local creation
			  else {
			    State state = new State(__uan, __ual);

			    //assume the reference is weak
			    muteGC();

			    //the source actor is  the startup actor
			    if (sourceActor == null) {
			      state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			    }

			    //the souce actor is a normal actor
			    else if (sourceActor instanceof UniversalActor.State) {

			      // this reference is part of garbage collection
			      activateGC();

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());

			      /* Garbage collection registration:
			       * register 'this reference' in sourceActor's forward list @
			       * register 'this reference' in the forward acquaintance's inverse list
			       */
			      String inverseRefString=null;
			      if (sourceActor.getUAN()!=null) {inverseRefString=sourceActor.getUAN().toString();}
			      else if (sourceActor.getUAL()!=null) {inverseRefString=sourceActor.getUAL().toString();}
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual != null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}
			      else {sourceActor.getActorMemory().getForwardList().putReference(state.getUAL());}

			      //put the inverse reference information in the actormemory
			      if (inverseRefString!=null) state.getActorMemory().getInverseList().putInverseReference(inverseRefString);
			    }
			    state.updateSelf(this);
			    ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			    if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
			  }
		}

		//creation invoked by a remote message
		else if (obj instanceof ActorReference) {
			  ActorReference sourceRef= (ActorReference) obj;
			  State state = new State(__uan, __ual);
			  muteGC();
			  state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			  if (sourceRef.getUAN() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAN());}
			  else if (sourceRef.getUAL() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAL());}
			  state.updateSelf(this);
			  ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(),state);
			  if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct() {
		Object[] __arguments = { };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor .State {
		public CausalAdvancedTodo self;
		public void updateSelf(ActorReference actorReference) {
			((CausalAdvancedTodo)actorReference).setUAL(getUAL());
			((CausalAdvancedTodo)actorReference).setUAN(getUAN());
			self = new CausalAdvancedTodo(false,getUAL());
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			self.activateGC();
		}

		public void preAct(String[] arguments) {
			getActorMemory().getInverseList().removeInverseReference("rmsp://me",1);
			{
				Object[] __args={arguments};
				self.send( new Message(self,self, "act", __args, null,null,false) );
			}
		}

		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "todo.CausalAdvancedTodo$State" );
			addMethodsForClasses();
		}

		public void construct() {}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Exception exception = null;

			if (matches != null) {
				if (!message.getMethodName().equals("die")) {activateArgsGC(message);}
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = (Exception)e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			System.err.println("Message processing exception:");
			if (message.getSource() != null) {
				System.err.println("\tSent by: " + message.getSource().toString());
			} else System.err.println("\tSent by: unknown");
			System.err.println("\tReceived by actor: " + toString());
			System.err.println("\tMessage: " + message.toString());
			if (exception == null) {
				if (matches == null) {
					System.err.println("\tNo methods with the same name found.");
					return;
				}
				System.err.println("\tDid not match any of the following: ");
				for (int i = 0; i < matches.length; i++) {
					System.err.print("\t\tMethod: " + matches[i].getName() + "( ");
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						System.err.print(parTypes[j].getName() + " ");
					}
					System.err.println(")");
				}
			} else {
				System.err.println("\tThrew exception: " + exception);
				exception.printStackTrace();
			}
		}

		public void chatSession(User s1, User s2, User s3, User s4, User s5, User s6, User s7, User s8, User s9, User s10, TaskList taskList) {
			{
				// s1<-setIsLeader()
				{
					Object _arguments[] = {  };
					Message message = new Message( self, s1, "setIsLeader", _arguments, null, null );
					__messages.add( message );
				}
			}
			ArrayList values = new ArrayList();
			values.add(1);
			values.add(2);
			values.add(3);
			values.add(4);
			values.add(5);
			values.add(6);
			values.add(7);
			values.add(8);
			values.add(9);
			values.add(10);
			Collections.shuffle(values);
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(0)+".", "username1", "u1t1", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(0)+".", "username1", "u1t1", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(1)+".", "username1", "u1t2", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(1)+".", "username1", "u1t2", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(2)+".", "username1", "u1t3", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(2)+".", "username1", "u1t3", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(3)+".", "username1", "u1t4", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(3)+".", "username1", "u1t4", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(4)+".", "username1", "u1t5", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(4)+".", "username1", "u1t5", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(5)+".", "username1", "u1t6", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(5)+".", "username1", "u1t6", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(6)+".", "username1", "u1t7", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(6)+".", "username1", "u1t7", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(7)+".", "username1", "u1t8", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(7)+".", "username1", "u1t8", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(8)+".", "username1", "u1t9", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(8)+".", "username1", "u1t9", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s1<-addTaskToList(taskList, "User 1: Initial Task "+values.get(9)+".", "username1", "u1t10", false, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 1: Initial Task "+values.get(9)+".", "username1", "u1t10", false, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s1, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			Collections.shuffle(values);
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(0)+".", "username2", "u2t1", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(0)+".", "username2", "u2t1", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(1)+".", "username2", "u2t2", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(1)+".", "username2", "u2t2", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(2)+".", "username2", "u2t3", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(2)+".", "username2", "u2t3", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(3)+".", "username2", "u2t4", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(3)+".", "username2", "u2t4", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(4)+".", "username2", "u2t5", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(4)+".", "username2", "u2t5", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(5)+".", "username2", "u2t6", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(5)+".", "username2", "u2t6", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(6)+".", "username2", "u2t7", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(6)+".", "username2", "u2t7", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(7)+".", "username2", "u2t8", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(7)+".", "username2", "u2t8", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(8)+".", "username2", "u2t9", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(8)+".", "username2", "u2t9", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s2<-addTaskToList(taskList, "User 2: Follow Up Task "+values.get(9)+".", "username2", "u2t10", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 2: Follow Up Task "+values.get(9)+".", "username2", "u2t10", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s2, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			Collections.shuffle(values);
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(0)+".", "username3", "u3t1", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(0)+".", "username3", "u3t1", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(1)+".", "username3", "u3t2", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(1)+".", "username3", "u3t2", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(2)+".", "username3", "u3t3", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(2)+".", "username3", "u3t3", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(3)+".", "username3", "u3t4", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(3)+".", "username3", "u3t4", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(4)+".", "username3", "u3t5", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(4)+".", "username3", "u3t5", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(5)+".", "username3", "u3t6", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(5)+".", "username3", "u3t6", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(6)+".", "username3", "u3t7", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(6)+".", "username3", "u3t7", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(7)+".", "username3", "u3t8", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(7)+".", "username3", "u3t8", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(8)+".", "username3", "u3t9", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(8)+".", "username3", "u3t9", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s3<-addTaskToList(taskList, "User 3: Follow Up Task "+values.get(9)+".", "username3", "u3t10", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 3: Follow Up Task "+values.get(9)+".", "username3", "u3t10", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s3, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			Collections.shuffle(values);
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(0)+".", "username4", "u4t1", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(0)+".", "username4", "u4t1", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(1)+".", "username4", "u4t2", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(1)+".", "username4", "u4t2", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(2)+".", "username4", "u4t3", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(2)+".", "username4", "u4t3", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(3)+".", "username4", "u4t4", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(3)+".", "username4", "u4t4", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(4)+".", "username4", "u4t5", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(4)+".", "username4", "u4t5", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(5)+".", "username4", "u4t6", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(5)+".", "username4", "u4t6", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(6)+".", "username4", "u4t7", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(6)+".", "username4", "u4t7", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(7)+".", "username4", "u4t8", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(7)+".", "username4", "u4t8", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(8)+".", "username4", "u4t9", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(8)+".", "username4", "u4t9", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s4<-addTaskToList(taskList, "User 4: Follow Up Task "+values.get(9)+".", "username4", "u4t10", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 4: Follow Up Task "+values.get(9)+".", "username4", "u4t10", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s4, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			Collections.shuffle(values);
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(0)+".", "username5", "u5t1", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(0)+".", "username5", "u5t1", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(1)+".", "username5", "u5t2", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(1)+".", "username5", "u5t2", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(2)+".", "username5", "u5t3", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(2)+".", "username5", "u5t3", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(3)+".", "username5", "u5t4", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(3)+".", "username5", "u5t4", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(4)+".", "username5", "u5t5", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(4)+".", "username5", "u5t5", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(5)+".", "username5", "u5t6", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(5)+".", "username5", "u5t6", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(6)+".", "username5", "u5t7", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(6)+".", "username5", "u5t7", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(7)+".", "username5", "u5t8", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(7)+".", "username5", "u5t8", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(8)+".", "username5", "u5t9", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(8)+".", "username5", "u5t9", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s5<-addTaskToList(taskList, "User 5: Follow Up Task "+values.get(9)+".", "username5", "u5t10", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 5: Follow Up Task "+values.get(9)+".", "username5", "u5t10", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s5, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			Collections.shuffle(values);
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(0)+".", "username6", "u6t1", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(0)+".", "username6", "u6t1", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(1)+".", "username6", "u6t2", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(1)+".", "username6", "u6t2", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(2)+".", "username6", "u6t3", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(2)+".", "username6", "u6t3", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(3)+".", "username6", "u6t4", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(3)+".", "username6", "u6t4", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(4)+".", "username6", "u6t5", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(4)+".", "username6", "u6t5", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(5)+".", "username6", "u6t6", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(5)+".", "username6", "u6t6", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(6)+".", "username6", "u6t7", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(6)+".", "username6", "u6t7", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(7)+".", "username6", "u6t8", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(7)+".", "username6", "u6t8", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(8)+".", "username6", "u6t9", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(8)+".", "username6", "u6t9", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s6<-addTaskToList(taskList, "User 6: Follow Up Task "+values.get(9)+".", "username6", "u6t10", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 6: Follow Up Task "+values.get(9)+".", "username6", "u6t10", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s6, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			Collections.shuffle(values);
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(0)+".", "username7", "u7t1", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(0)+".", "username7", "u7t1", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(1)+".", "username7", "u7t2", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(1)+".", "username7", "u7t2", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(2)+".", "username7", "u7t3", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(2)+".", "username7", "u7t3", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(3)+".", "username7", "u7t4", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(3)+".", "username7", "u7t4", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(4)+".", "username7", "u7t5", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(4)+".", "username7", "u7t5", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(5)+".", "username7", "u7t6", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(5)+".", "username7", "u7t6", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(6)+".", "username7", "u7t7", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(6)+".", "username7", "u7t7", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(7)+".", "username7", "u7t8", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(7)+".", "username7", "u7t8", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(8)+".", "username7", "u7t9", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(8)+".", "username7", "u7t9", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s7<-addTaskToList(taskList, "User 7: Follow Up Task "+values.get(9)+".", "username7", "u7t10", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 7: Follow Up Task "+values.get(9)+".", "username7", "u7t10", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s7, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			Collections.shuffle(values);
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(0)+".", "username8", "u8t1", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(0)+".", "username8", "u8t1", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(1)+".", "username8", "u8t2", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(1)+".", "username8", "u8t2", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(2)+".", "username8", "u8t3", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(2)+".", "username8", "u8t3", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(3)+".", "username8", "u8t4", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(3)+".", "username8", "u8t4", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(4)+".", "username8", "u8t5", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(4)+".", "username8", "u8t5", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(5)+".", "username8", "u8t6", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(5)+".", "username8", "u8t6", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(6)+".", "username8", "u8t7", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(6)+".", "username8", "u8t7", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(7)+".", "username8", "u8t8", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(7)+".", "username8", "u8t8", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(8)+".", "username8", "u8t9", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(8)+".", "username8", "u8t9", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s8<-addTaskToList(taskList, "User 8: Follow Up Task "+values.get(9)+".", "username8", "u8t10", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 8: Follow Up Task "+values.get(9)+".", "username8", "u8t10", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s8, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			Collections.shuffle(values);
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(0)+".", "username9", "u9t1", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(0)+".", "username9", "u9t1", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(1)+".", "username9", "u9t2", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(1)+".", "username9", "u9t2", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(2)+".", "username9", "u9t3", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(2)+".", "username9", "u9t3", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(3)+".", "username9", "u9t4", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(3)+".", "username9", "u9t4", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(4)+".", "username9", "u9t5", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(4)+".", "username9", "u9t5", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(5)+".", "username9", "u9t6", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(5)+".", "username9", "u9t6", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(6)+".", "username9", "u9t7", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(6)+".", "username9", "u9t7", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(7)+".", "username9", "u9t8", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(7)+".", "username9", "u9t8", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(8)+".", "username9", "u9t9", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(8)+".", "username9", "u9t9", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s9<-addTaskToList(taskList, "User 9: Follow Up Task "+values.get(9)+".", "username9", "u9t10", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 9: Follow Up Task "+values.get(9)+".", "username9", "u9t10", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s9, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			Collections.shuffle(values);
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(0)+".", "username10", "u10t1", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(0)+".", "username10", "u10t1", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(1)+".", "username10", "u10t2", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(1)+".", "username10", "u10t2", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(2)+".", "username10", "u10t3", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(2)+".", "username10", "u10t3", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(3)+".", "username10", "u10t4", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(3)+".", "username10", "u10t4", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(4)+".", "username10", "u10t5", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(4)+".", "username10", "u10t5", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(5)+".", "username10", "u10t6", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(5)+".", "username10", "u10t6", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(6)+".", "username10", "u10t7", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(6)+".", "username10", "u10t7", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(7)+".", "username10", "u10t8", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(7)+".", "username10", "u10t8", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(8)+".", "username10", "u10t9", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(8)+".", "username10", "u10t9", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// s10<-addTaskToList(taskList, "User 10: Follow Up Task "+values.get(9)+".", "username10", "u10t10", true, 10, 90, true)
				{
					Object _arguments[] = { taskList, "User 10: Follow Up Task "+values.get(9)+".", "username10", "u10t10", true, new Integer(10), new Integer(90), true };
					Message message = new Message( self, s10, "addTaskToList", _arguments, null, null );
					__messages.add( message );
				}
			}
		}
		public void reply(String replyMsg) {
			{
				// standardOutput<-println(replyMsg)
				{
					Object _arguments[] = { replyMsg };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
		}
		public void act(String args[]) {
			try {
				User user1 = (User)User.getReferenceByName(args[0]);
				User user2 = (User)User.getReferenceByName(args[1]);
				User user3 = (User)User.getReferenceByName(args[2]);
				User user4 = (User)User.getReferenceByName(args[3]);
				User user5 = (User)User.getReferenceByName(args[4]);
				User user6 = (User)User.getReferenceByName(args[5]);
				User user7 = (User)User.getReferenceByName(args[6]);
				User user8 = (User)User.getReferenceByName(args[7]);
				User user9 = (User)User.getReferenceByName(args[8]);
				User user10 = (User)User.getReferenceByName(args[9]);
				TaskList taskList = (TaskList)TaskList.getReferenceByName(args[10]);
				Date first = new Date();
				Timestamp start = new Timestamp(first.getTime());
				{
					// standardOutput<-println("Starting time: "+start)
					{
						Object _arguments[] = { "Starting time: "+start };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
				Instant begin = Instant.now();
				{
					Token token_3_0 = new Token();
					Token token_3_1 = new Token();
					// chatSession(user1, user2, user3, user4, user5, user6, user7, user8, user9, user10, taskList)
					{
						Object _arguments[] = { user1, user2, user3, user4, user5, user6, user7, user8, user9, user10, taskList };
						Message message = new Message( self, self, "chatSession", _arguments, null, token_3_0 );
						__messages.add( message );
					}
					// trackEndingTime(begin)
					{
						Object _arguments[] = { begin };
						Message message = new Message( self, self, "trackEndingTime", _arguments, token_3_0, token_3_1 );
						__messages.add( message );
					}
					// standardOutput<-println("Done with user conversation")
					{
						Object _arguments[] = { "Done with user conversation" };
						Message message = new Message( self, standardOutput, "println", _arguments, token_3_1, null );
						__messages.add( message );
					}
				}
			}
			catch (Exception e) {
				{
					// standardOutput<-println("Usage: java todo.Chat <userUAN1> <userUAN2> <taskListUAN3> <taskUAN4> <taskUAN5>")
					{
						Object _arguments[] = { "Usage: java todo.Chat <userUAN1> <userUAN2> <taskListUAN3> <taskUAN4> <taskUAN5>" };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
				return;
			}

		}
		public void trackEndingTime(Instant begin) {
			Date second = new Date();
			Timestamp end = new Timestamp(second.getTime());
			Instant endTime = Instant.now();
			Duration timeDifference = Duration.between(begin, endTime);
			long timeTaken = timeDifference.toMillis();
			{
				// standardOutput<-println("Time taken to run this in milliseconds: "+timeTaken)
				{
					Object _arguments[] = { "Time taken to run this in milliseconds: "+timeTaken };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// standardOutput<-println("Ending time: "+end)
				{
					Object _arguments[] = { "Ending time: "+end };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
		}
	}
}