package todo;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import gc.WeakReference;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

import salsa.resources.SystemService;

import salsa.resources.ActorService;

// End SALSA compiler generated import delcarations.

import java.util.Set;
import java.util.HashSet;
import java.util.Date;
import java.sql.Timestamp;
import java.util.Iterator;
import java.util.Queue;
import java.util.LinkedList;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

public class User extends UniversalActor  implements ActorService {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getTheater().getLocation() + System.getProperty("identifier"));
		}
		User instance = (User)new User(uan, ual,null).construct();
		{
			Object[] _arguments = { args };
			instance.send( new Message(instance, instance, "act", _arguments, null, null) );
		}
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new User(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return User.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new User(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return User.getReferenceByLocation(new UAL(ual)); }
	public User(boolean o, UAN __uan)	{ super(false,__uan); }
	public User(boolean o, UAL __ual)	{ super(false,__ual); }

	public User(UAN __uan,UniversalActor.State sourceActor)	{ this(__uan, null,null); }
	public User(UAL __ual,UniversalActor.State sourceActor)	{ this(null, __ual,null); }
	public User(UniversalActor.State sourceActor)		{ this(null, null,null);  }
	public User()		{  }
	public User(UAN __uan, UAL __ual,Object sourceActor) {
		if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {
			createRemotely(__uan, __ual, "todo.User");
		} else {
			State state = new State(__uan, __ual);
			state.updateSelf(this);
			ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct (String id, String email, String status) {
		Object[] __arguments = { id, email, status };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public UniversalActor construct() {
		Object[] __arguments = { };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor .State implements salsa.resources.ActorServiceState {
		public User self;
		public void updateSelf(ActorReference actorReference) {
			((User)actorReference).setUAL(getUAL());
			((User)actorReference).setUAN(getUAN());
			self = new User(false,getUAL());
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			self.muteGC();
		}

		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "todo.User$State" );
			addMethodsForClasses();
		}

		public void construct() {}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Exception exception = null;

			if (matches != null) {
				if (!message.getMethodName().equals("die")) {activateArgsGC(message);}
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = (Exception)e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			System.err.println("Message processing exception:");
			if (message.getSource() != null) {
				System.err.println("\tSent by: " + message.getSource().toString());
			} else System.err.println("\tSent by: unknown");
			System.err.println("\tReceived by actor: " + toString());
			System.err.println("\tMessage: " + message.toString());
			if (exception == null) {
				if (matches == null) {
					System.err.println("\tNo methods with the same name found.");
					return;
				}
				System.err.println("\tDid not match any of the following: ");
				for (int i = 0; i < matches.length; i++) {
					System.err.print("\t\tMethod: " + matches[i].getName() + "( ");
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						System.err.print(parTypes[j].getName() + " ");
					}
					System.err.println(")");
				}
			} else {
				System.err.println("\tThrew exception: " + exception);
				exception.printStackTrace();
			}
		}

		String myName = "";
		String emailId = "";
		String status = "";
		Server server_ref;
		boolean isLeader = false;
		ArrayList initialList = new ArrayList();
		Queue waitQueue = new LinkedList();
		Queue messageQueue = new LinkedList();
		Map fifoValues = new HashMap();
		Map fifoMessageValues = new HashMap();
		Map valuesAdded = new HashMap();
		ArrayList tasks = new ArrayList();
		void construct(String id, String email, String status){
			myName = id;
			emailId = email;
			status = status;
		}
		public void setIsLeader() {
			isLeader = true;
		}
		public boolean handleFifoCode(Task task, String taskName, String text, boolean isFollowup, boolean original) throws InterruptedException{
			Integer current_value = Integer.parseInt(text.substring(10).replaceAll("[\\D]", ""));
			Integer current_user = Integer.parseInt(text.substring(0, 10).replaceAll("[\\D]", ""));
			if (!valuesAdded.containsKey(current_user)) {{
				ArrayList vals = new ArrayList();
				valuesAdded.put(current_user, vals);
			}
}			if (!fifoValues.containsKey(current_user)) {{
				ArrayList vals = new ArrayList();
				ArrayList msgVals = new ArrayList();
				fifoValues.put(current_user, vals);
				fifoMessageValues.put(current_user, msgVals);
			}
}			ArrayList currentAdded = (ArrayList)valuesAdded.get(current_user);
			ArrayList currentFifo = (ArrayList)fifoValues.get(current_user);
			ArrayList currentFifoMessages = (ArrayList)fifoMessageValues.get(current_user);
			boolean isAdded = false;
			if ((currentAdded.size()==0&&current_value==1)||(currentAdded.size()>0&&((Integer)currentAdded.get(currentAdded.size()-1)==current_value-1))) {{
				currentAdded.add(current_value);
				tasks.add(text);
				Thread.sleep(200);
				Date date_four = new Date();
				Timestamp current_four = new Timestamp(date_four.getTime());
				if (original) {initialList.add(text);
}				String follow_up = "";
				if (!isFollowup) {follow_up = "Initial Task";
}				else {follow_up = "Follow Up Task";
}				{
					// standardOutput<-println("[Speaker Remote] "+myName+": "+"Add Message: "+"Task name: "+taskName+"Task type: "+follow_up+"; Task text: "+text+"; Timestamp: "+current_four)
					{
						Object _arguments[] = { "[Speaker Remote] "+myName+": "+"Add Message: "+"Task name: "+taskName+"Task type: "+follow_up+"; Task text: "+text+"; Timestamp: "+current_four };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
				int i = -1;
				for (i = 0; i<currentFifo.size(); i++){
					if ((Integer)currentFifo.get(i)==current_value+1) {{
						current_value = (Integer)currentFifo.get(i);
						String current_task_message = (String)currentFifoMessages.get(i);
						currentAdded.add(current_value);
						tasks.add(current_task_message);
						Thread.sleep(200);
						Date date_five = new Date();
						Timestamp current_five = new Timestamp(date_five.getTime());
						follow_up = "";
						if (!isFollowup) {follow_up = "Initial Task";
}						else {follow_up = "Follow Up Task";
}						if (original) {initialList.add(current_task_message);
}						{
							// standardOutput<-println("[Speaker Remote] "+myName+": "+"Add Message: "+"Task name: "+taskName+"Task type: "+follow_up+"; Task text: "+current_task_message+"; Timestamp: "+current_five)
							{
								Object _arguments[] = { "[Speaker Remote] "+myName+": "+"Add Message: "+"Task name: "+taskName+"Task type: "+follow_up+"; Task text: "+current_task_message+"; Timestamp: "+current_five };
								Message message = new Message( self, standardOutput, "println", _arguments, null, null );
								__messages.add( message );
							}
						}
					}
}					else {break;}				}
				while (i>0) {
					currentFifoMessages.remove(0);
					currentFifo.remove(0);
					i--;
				}
				isAdded = true;
			}
}			else {{
				if (currentFifo.size()==0) {{
					currentFifo.add(current_value);
					currentFifoMessages.add(text);
				}
}				else {{
					if (current_value<(Integer)currentFifo.get(0)) {{
						currentFifo.add(0, current_value);
						currentFifoMessages.add(0, text);
					}
}					else {{
						int i = -1;
						boolean added = false;
						for (i = 0; i<currentFifo.size(); i++){
							if (current_value<(Integer)currentFifo.get(i)) {{
								added = true;
								currentFifo.add(i, current_value);
								currentFifoMessages.add(i, text);
break;							}
}						}
						if (!added) {{
							currentFifo.add(i, current_value);
							currentFifoMessages.add(i, text);
						}
}					}
}				}
}			}
}			valuesAdded.put(current_user, currentAdded);
			fifoValues.put(current_user, currentFifo);
			fifoMessageValues.put(current_user, currentFifoMessages);
			return isAdded;
		}
		public boolean handleFifoCodeAdvanced(Task task, String taskName, String text, boolean isFollowup, boolean original) throws InterruptedException{
			Integer current_value = Integer.parseInt(text.substring(10).replaceAll("[\\D]", ""));
			Integer current_user = Integer.parseInt(text.substring(0, 10).replaceAll("[\\D]", ""));
			if (!valuesAdded.containsKey(current_user)) {{
				ArrayList vals = new ArrayList();
				valuesAdded.put(current_user, vals);
			}
}			if (!fifoValues.containsKey(current_user)) {{
				ArrayList vals = new ArrayList();
				ArrayList msgVals = new ArrayList();
				fifoValues.put(current_user, vals);
				fifoMessageValues.put(current_user, msgVals);
			}
}			ArrayList currentAdded = (ArrayList)valuesAdded.get(current_user);
			ArrayList currentFifo = (ArrayList)fifoValues.get(current_user);
			ArrayList currentFifoMessages = (ArrayList)fifoMessageValues.get(current_user);
			boolean isAdded = false;
			if ((currentAdded.size()==0&&current_value==1)||(currentAdded.size()>0&&((Integer)currentAdded.get(currentAdded.size()-1)==current_value-1))) {{
				currentAdded.add(current_value);
				messageQueue.add(text);
				if (original) {initialList.add(text);
}				int i = -1;
				for (i = 0; i<currentFifo.size(); i++){
					if ((Integer)currentFifo.get(i)==current_value+1) {{
						current_value = (Integer)currentFifo.get(i);
						String current_task_message = (String)currentFifoMessages.get(i);
						currentAdded.add(current_value);
						if (original) {initialList.add(current_task_message);
}						messageQueue.add(current_task_message);
					}
}					else {break;}				}
				while (i>0) {
					currentFifoMessages.remove(0);
					currentFifo.remove(0);
					i--;
				}
				isAdded = true;
			}
}			else {{
				if (currentFifo.size()==0) {{
					currentFifo.add(current_value);
					currentFifoMessages.add(text);
				}
}				else {{
					if (current_value<(Integer)currentFifo.get(0)) {{
						currentFifo.add(0, current_value);
						currentFifoMessages.add(0, text);
					}
}					else {{
						int i = -1;
						boolean added = false;
						for (i = 0; i<currentFifo.size(); i++){
							if (current_value<(Integer)currentFifo.get(i)) {{
								added = true;
								currentFifo.add(i, current_value);
								currentFifoMessages.add(i, text);
break;							}
}						}
						if (!added) {{
							currentFifo.add(i, current_value);
							currentFifoMessages.add(i, text);
						}
}					}
}				}
}			}
}			valuesAdded.put(current_user, currentAdded);
			fifoValues.put(current_user, currentFifo);
			fifoMessageValues.put(current_user, currentFifoMessages);
			return isAdded;
		}
		public void broadcastReceive(Task task, String taskName, String text, boolean update, int number_of_initials, int total_updates, boolean isFollowup, boolean fifo) throws InterruptedException{
			if (update) {{
				for (int i = 0; i<tasks.size(); i++){
					Task storedTask = (Task)tasks.get(i);
					if (taskName.equals(storedTask.getTaskName())) {{
						storedTask.updateTask(text);
						String follow_up = "";
						if (!isFollowup) {follow_up = "Initial Task";
}						else {follow_up = "Follow Up Task";
}						Thread.sleep(200);
						Date date = new Date();
						Timestamp current = new Timestamp(date.getTime());
						{
							// standardOutput<-println("[Speaker Remote] "+myName+": "+"Upd Message: "+"Task name: "+taskName+"Task type: "+follow_up+"; Task text: "+text+"; Timestamp: "+current)
							{
								Object _arguments[] = { "[Speaker Remote] "+myName+": "+"Upd Message: "+"Task name: "+taskName+"Task type: "+follow_up+"; Task text: "+text+"; Timestamp: "+current };
								Message message = new Message( self, standardOutput, "println", _arguments, null, null );
								__messages.add( message );
							}
						}
break;					}
}				}
			}
}			else {{
				if (number_of_initials==0) {{
					if (!fifo) {{
						tasks.add(task);
						String follow_up = "";
						if (!isFollowup) {follow_up = "Initial Task";
}						else {follow_up = "Follow Up Task";
}						Thread.sleep(200);
						Date date = new Date();
						Timestamp current = new Timestamp(date.getTime());
						{
							// standardOutput<-println("[Speaker Remote] "+myName+": "+"Add Message: "+"Task name: "+task.getTaskName()+"Task type: "+follow_up+"; Task text: "+task.getTaskText()+"; Timestamp: "+current)
							{
								Object _arguments[] = { "[Speaker Remote] "+myName+": "+"Add Message: "+"Task name: "+task.getTaskName()+"Task type: "+follow_up+"; Task text: "+task.getTaskText()+"; Timestamp: "+current };
								Message message = new Message( self, standardOutput, "println", _arguments, null, null );
								__messages.add( message );
							}
						}
					}
}					else {					{
						// handleFifoCode(task, taskName, text, isFollowup, false)
						{
							Object _arguments[] = { task, taskName, text, isFollowup, false };
							Message message = new Message( self, self, "handleFifoCode", _arguments, null, null );
							__messages.add( message );
						}
					}
}				}
}				else {{
					if (isFollowup) {{
						double number_users = (total_updates+number_of_initials)/number_of_initials;
						double total_initials = number_users*0.1*number_of_initials;
						if (initialList.size()==total_initials||(isLeader&&initialList.size()==(int)(total_initials-number_of_initials))) {{
							if (waitQueue.size()>0) {{
								while (waitQueue.size()>0) {
									String currentTaskMessage = (String)waitQueue.remove();
									{
										// handleFifoCode(task, taskName, currentTaskMessage, isFollowup, false)
										{
											Object _arguments[] = { task, taskName, currentTaskMessage, isFollowup, false };
											Message message = new Message( self, self, "handleFifoCode", _arguments, null, null );
											__messages.add( message );
										}
									}
								}
							}
}							{
								// handleFifoCode(task, taskName, text, isFollowup, false)
								{
									Object _arguments[] = { task, taskName, text, isFollowup, false };
									Message message = new Message( self, self, "handleFifoCode", _arguments, null, null );
									__messages.add( message );
								}
							}
						}
}						else {{
							waitQueue.add(text);
						}
}					}
}					else {{
						{
							Token token_5_0 = new Token();
							// handleFifoCode(task, taskName, text, isFollowup, true)
							{
								Object _arguments[] = { task, taskName, text, isFollowup, true };
								Message message = new Message( self, self, "handleFifoCode", _arguments, null, token_5_0 );
								__messages.add( message );
							}
							// handleNormalStall(task, taskName, number_of_initials, total_updates)
							{
								Object _arguments[] = { task, taskName, number_of_initials, total_updates };
								Message message = new Message( self, self, "handleNormalStall", _arguments, token_5_0, null );
								__messages.add( message );
							}
						}
					}
}				}
}			}
}		}
		public void handleNormalStall(Task task, String taskName, int number_of_initials, int total_updates) {
			double number_users = (total_updates+number_of_initials)/number_of_initials;
			double total_initials = number_users*0.1*number_of_initials;
			if (initialList.size()==total_initials||(isLeader&&initialList.size()==(int)(total_initials-number_of_initials))) {{
				if (waitQueue.size()>0) {{
					while (waitQueue.size()>0) {
						String currentTaskMessage = (String)waitQueue.remove();
						{
							// handleFifoCode(task, taskName, currentTaskMessage, true, false)
							{
								Object _arguments[] = { task, taskName, currentTaskMessage, true, false };
								Message message = new Message( self, self, "handleFifoCode", _arguments, null, null );
								__messages.add( message );
							}
						}
					}
				}
}			}
}		}
		public void broadcastReceiveAdvanced(Task task, String taskName, String text, boolean update, int number_of_initials, int total_updates, boolean isFollowup, boolean fifo) throws InterruptedException{
			if (number_of_initials==0) {{
				if (!fifo) {{
					messageQueue.add(task);
				}
}				else {{
					{
						// handleFifoAdvanced(task, taskName, text, isFollowup, false)
						{
							Object _arguments[] = { task, taskName, text, isFollowup, false };
							Message message = new Message( self, self, "handleFifoAdvanced", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}			}
}			else {{
				if (isFollowup) {{
					{
						Token token_4_0 = new Token();
						// handleFollowCase(task, taskName, text, number_of_initials, total_updates)
						{
							Object _arguments[] = { task, taskName, text, number_of_initials, total_updates };
							Message message = new Message( self, self, "handleFollowCase", _arguments, null, token_4_0 );
							__messages.add( message );
						}
						// printQueueInfo(total_updates)
						{
							Object _arguments[] = { total_updates };
							Message message = new Message( self, self, "printQueueInfo", _arguments, token_4_0, null );
							__messages.add( message );
						}
					}
				}
}				else {{
					{
						Token token_4_0 = new Token();
						Token token_4_1 = new Token();
						// handleFifoCodeAdvanced(task, taskName, text, isFollowup, true)
						{
							Object _arguments[] = { task, taskName, text, isFollowup, true };
							Message message = new Message( self, self, "handleFifoCodeAdvanced", _arguments, null, token_4_0 );
							__messages.add( message );
						}
						// handleAdvancedStall(task, taskName, number_of_initials, total_updates)
						{
							Object _arguments[] = { task, taskName, number_of_initials, total_updates };
							Message message = new Message( self, self, "handleAdvancedStall", _arguments, token_4_0, token_4_1 );
							__messages.add( message );
						}
						// printQueueInfo(total_updates)
						{
							Object _arguments[] = { total_updates };
							Message message = new Message( self, self, "printQueueInfo", _arguments, token_4_1, null );
							__messages.add( message );
						}
					}
				}
}			}
}		}
		public void handleFollowCase(Task task, String taskName, String text, int number_of_initials, int total_updates) {
			double number_users = (total_updates+number_of_initials)/number_of_initials;
			double total_initials = number_users*0.1*number_of_initials;
			if (initialList.size()==total_initials||(isLeader&&initialList.size()==(int)(total_initials-number_of_initials))) {{
				if (waitQueue.size()>0) {{
					while (waitQueue.size()>0) {
						String currentTaskMessage = (String)waitQueue.remove();
						{
							// handleFifoCodeAdvanced(task, taskName, currentTaskMessage, true, false)
							{
								Object _arguments[] = { task, taskName, currentTaskMessage, true, false };
								Message message = new Message( self, self, "handleFifoCodeAdvanced", _arguments, null, null );
								__messages.add( message );
							}
						}
					}
				}
}				{
					// handleFifoCodeAdvanced(task, taskName, text, true, false)
					{
						Object _arguments[] = { task, taskName, text, true, false };
						Message message = new Message( self, self, "handleFifoCodeAdvanced", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
}			else {{
				waitQueue.add(text);
			}
}		}
		public void handleAdvancedStall(Task task, String taskName, int number_of_initials, int total_updates) {
			double number_users = (total_updates+number_of_initials)/number_of_initials;
			double total_initials = number_users*0.1*number_of_initials;
			if (initialList.size()==total_initials||(isLeader&&initialList.size()==(int)(total_initials-number_of_initials))) {{
				if (waitQueue.size()>0) {{
					while (waitQueue.size()>0) {
						String currentTaskMessage = (String)waitQueue.remove();
						{
							// handleFifoCodeAdvanced(task, taskName, currentTaskMessage, true, false)
							{
								Object _arguments[] = { task, taskName, currentTaskMessage, true, false };
								Message message = new Message( self, self, "handleFifoCodeAdvanced", _arguments, null, null );
								__messages.add( message );
							}
						}
					}
				}
}			}
}		}
		public void printQueueInfo(int total_updates) throws InterruptedException{
			{
				// standardOutput<-println(messageQueue.size())
				{
					Object _arguments[] = { messageQueue.size() };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
			if (messageQueue.size()==total_updates) {{
				while (messageQueue.size()>0) {
					tasks.add(messageQueue.remove());
					Thread.sleep(200);
				}
				Date date = new Date();
				Timestamp current = new Timestamp(date.getTime());
				{
					// standardOutput<-println("Overall Timestamp: "+current)
					{
						Object _arguments[] = { "Overall Timestamp: "+current };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
				for (int i = 0; i<tasks.size(); i++){
					String follow_up = "";
					Task currentTask = (Task)tasks.get(i);
					if (currentTask.getFollowtype()) {follow_up = "Follow Up Task";
}					else {follow_up = "Initial Task";
}					{
						// standardOutput<-println("Task type: "+follow_up+"; Task text: "+currentTask.getTaskText())
						{
							Object _arguments[] = { "Task type: "+follow_up+"; Task text: "+currentTask.getTaskText() };
							Message message = new Message( self, standardOutput, "println", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
			}
}		}
		public String getUserName() {
			return myName;
		}
		public void whereAmI() {
			{
				// standardOutput<-println("User started with uan: "+getUAN().toString())
				{
					Object _arguments[] = { "User started with uan: "+getUAN().toString() };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
		}
		public boolean addTaskToList(TaskList taskList, String text, String creator, String name, boolean isFollowup, int number_of_initials, int total_updates, boolean fifo) {
			Date date = new Date();
			Timestamp current = new Timestamp(date.getTime());
			String follow_up = "";
			if (isFollowup) {follow_up = "Follow Up Task";
}			else {follow_up = "Initial Task";
}			Task task = new Task(text, creator, name, isFollowup);
			{
				Token token_2_0 = new Token();
				// standardOutput<-println("[Speaker Local] "+myName+": "+"Add message: "+"Task name: "+name+"Task type: "+follow_up+"; Task text: "+task.getTaskText()+"; Timestamp: "+current)
				{
					Object _arguments[] = { "[Speaker Local] "+myName+": "+"Add message: "+"Task name: "+name+"Task type: "+follow_up+"; Task text: "+task.getTaskText()+"; Timestamp: "+current };
					Message message = new Message( self, standardOutput, "println", _arguments, null, token_2_0 );
					__messages.add( message );
				}
				// server_ref<-addTaskToList(taskList, task, name, text, myName, total_updates, number_of_initials, isFollowup, fifo)
				{
					Object _arguments[] = { taskList, task, name, text, myName, total_updates, number_of_initials, isFollowup, fifo };
					Message message = new Message( self, server_ref, "addTaskToList", _arguments, token_2_0, null );
					__messages.add( message );
				}
			}
			return true;
		}
		public boolean updateTask(Task task, String text, String name, int number_of_initials, int total_updates) {
			Date date = new Date();
			Timestamp current = new Timestamp(date.getTime());
			{
				Token token_2_0 = new Token();
				// standardOutput<-println("[Speaker Local] "+myName+": "+"Upd message: "+"Task name: "+name+"Task type: Initial task"+"; Task text: "+text+"; Timestamp: "+current)
				{
					Object _arguments[] = { "[Speaker Local] "+myName+": "+"Upd message: "+"Task name: "+name+"Task type: Initial task"+"; Task text: "+text+"; Timestamp: "+current };
					Message message = new Message( self, standardOutput, "println", _arguments, null, token_2_0 );
					__messages.add( message );
				}
				// server_ref<-updateTask(task, name, text, myName, total_updates, number_of_initials, true)
				{
					Object _arguments[] = { task, name, text, myName, total_updates, number_of_initials, true };
					Message message = new Message( self, server_ref, "updateTask", _arguments, token_2_0, null );
					__messages.add( message );
				}
			}
			return true;
		}
		public void act(String args[]) {
			if (args.length!=2) {{
				{
					// standardOutput<-println("Usage: java -Duan=uan://hostname/place todo.User <serverName> <myName>")
					{
						Object _arguments[] = { "Usage: java -Duan=uan://hostname/place todo.User <serverName> <myName>" };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
				return;
			}
}			myName = args[1];
			server_ref = (Server)Server.getReferenceByName(args[0]);
			{
				Token token_2_0 = new Token();
				// whereAmI()
				{
					Object _arguments[] = {  };
					Message message = new Message( self, self, "whereAmI", _arguments, null, token_2_0 );
					__messages.add( message );
				}
				// standardOutput<-println("Messaging server")
				{
					Object _arguments[] = { "Messaging server" };
					Message message = new Message( self, standardOutput, "println", _arguments, token_2_0, null );
					__messages.add( message );
				}
			}
			{
				Token token_2_0 = new Token();
				// server_ref<-registerUser(myName, emailId, status, ((User)self))
				{
					Object _arguments[] = { myName, emailId, status, ((User)self) };
					Message message = new Message( self, server_ref, "registerUser", _arguments, null, token_2_0 );
					__messages.add( message );
				}
				// standardOutput<-println("Finished registering")
				{
					Object _arguments[] = { "Finished registering" };
					Message message = new Message( self, standardOutput, "println", _arguments, token_2_0, null );
					__messages.add( message );
				}
			}
		}
	}
}